{
 "title": "Demo - Stocks",
 "time": { "from": "2022-03-25T00:40:28.410Z", "to": "2022-03-25T05:28:08.512Z" },
 "templating": {
  "list": [
   {
    "name": "Code1",
    "label": "Code1",
    "query": "from(bucket:\"sino_quotes\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"h_tick\")\r\n  |> last()\r\n  |> keep(columns: [\"code\"])\r\n  |> group()\r\n  |> distinct(column: \"code\")\r\n  "
   },
   {
    "name": "Code2",
    "label": "Code2",
    "query": "from(bucket:\"sino_quotes\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"h_tick\")\r\n  |> last()\r\n  |> keep(columns: [\"code\"])\r\n  |> group()\r\n  |> distinct(column: \"code\")\r\n  "
   },
   {
    "name": "Code3",
    "label": "Code3",
    "query": "from(bucket:\"sino_quotes\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"h_tick\")\r\n  |> last()\r\n  |> keep(columns: [\"code\"])\r\n  |> group()\r\n  |> distinct(column: \"code\")\r\n  "
   },
   {
    "name": "Code4",
    "label": "Code4",
    "query": "from(bucket:\"sino_quotes\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"h_tick\")\r\n  |> last()\r\n  |> keep(columns: [\"code\"])\r\n  |> group()\r\n  |> distinct(column: \"code\")\r\n  "
   },
   { "name": "Kbar_Freq", "query": "1s, 1m, 5m, 15m, 1h, 1d" }
  ]
 },
 "panels": [
  {
   "title": "(1)  ${Code1}",
   "type": "candlestick",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "data = from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"h_tick\")\r\n  |> filter(fn: (r) => r.code == ${Code1:doublequote})\r\n  |> filter(fn: (r) => r._field == \"close\")\r\n  |> drop(columns: [\"code\", \"_measurement\"])\r\n\r\ndata_open = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: first)\r\n  |> set(key: \"_field\", value: \"open\")\r\n\r\ndata_close = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: last)\r\n  |> set(key: \"_field\", value: \"close\")\r\n\r\ndata_high = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: max)\r\n  |> set(key: \"_field\", value: \"high\")\r\n\r\ndata_low = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: min)\r\n  |> set(key: \"_field\", value: \"low\")\r\n\r\n\r\ndata_vol = from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"h_tick\")\r\n  |> filter(fn: (r) => r.code == ${Code1:doublequote})\r\n  |> filter(fn: (r) => r._field == \"vol\")\r\n  |> drop(columns: [\"code\", \"_measurement\"])\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: sum)\r\n  |> set(key: \"_field\", value: \"volume\")\r\n\r\nunion(tables: [data_open, data_close, data_high, data_low, data_vol])\r\n"
    }
   ]
  },
  {
   "title": "(2)  ${Code2}",
   "type": "candlestick",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "data = from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"h_tick\")\r\n  |> filter(fn: (r) => r.code == ${Code2:doublequote})\r\n  |> filter(fn: (r) => r._field == \"close\")\r\n  |> drop(columns: [\"code\", \"_measurement\"])\r\n\r\ndata_open = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: first)\r\n  |> set(key: \"_field\", value: \"open\")\r\n\r\ndata_close = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: last)\r\n  |> set(key: \"_field\", value: \"close\")\r\n\r\ndata_high = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: max)\r\n  |> set(key: \"_field\", value: \"high\")\r\n\r\ndata_low = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: min)\r\n  |> set(key: \"_field\", value: \"low\")\r\n\r\n\r\ndata_vol = from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"h_tick\")\r\n  |> filter(fn: (r) => r.code == ${Code2:doublequote})\r\n  |> filter(fn: (r) => r._field == \"vol\")\r\n  |> drop(columns: [\"code\", \"_measurement\"])\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: sum)\r\n  |> set(key: \"_field\", value: \"volume\")\r\n\r\nunion(tables: [data_open, data_close, data_high, data_low, data_vol])\r\n"
    }
   ]
  },
  {
   "title": "(3)  ${Code3}",
   "type": "candlestick",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "data = from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"h_tick\")\r\n  |> filter(fn: (r) => r.code == ${Code3:doublequote})\r\n  |> filter(fn: (r) => r._field == \"close\")\r\n  |> drop(columns: [\"code\", \"_measurement\"])\r\n\r\ndata_open = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: first)\r\n  |> set(key: \"_field\", value: \"open\")\r\n\r\ndata_close = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: last)\r\n  |> set(key: \"_field\", value: \"close\")\r\n\r\ndata_high = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: max)\r\n  |> set(key: \"_field\", value: \"high\")\r\n\r\ndata_low = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: min)\r\n  |> set(key: \"_field\", value: \"low\")\r\n\r\n\r\ndata_vol = from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"h_tick\")\r\n  |> filter(fn: (r) => r.code == ${Code3:doublequote})\r\n  |> filter(fn: (r) => r._field == \"vol\")\r\n  |> drop(columns: [\"code\", \"_measurement\"])\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: sum)\r\n  |> set(key: \"_field\", value: \"volume\")\r\n\r\nunion(tables: [data_open, data_close, data_high, data_low, data_vol])\r\n"
    }
   ]
  },
  {
   "title": "(4)  ${Code4}",
   "type": "candlestick",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "query": "data = from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"h_tick\")\r\n  |> filter(fn: (r) => r.code == ${Code4:doublequote})\r\n  |> filter(fn: (r) => r._field == \"close\")\r\n  |> drop(columns: [\"code\", \"_measurement\"])\r\n\r\ndata_open = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: first)\r\n  |> set(key: \"_field\", value: \"open\")\r\n\r\ndata_close = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: last)\r\n  |> set(key: \"_field\", value: \"close\")\r\n\r\ndata_high = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: max)\r\n  |> set(key: \"_field\", value: \"high\")\r\n\r\ndata_low = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: min)\r\n  |> set(key: \"_field\", value: \"low\")\r\n\r\n\r\ndata_vol = from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"h_tick\")\r\n  |> filter(fn: (r) => r.code == ${Code4:doublequote})\r\n  |> filter(fn: (r) => r._field == \"vol\")\r\n  |> drop(columns: [\"code\", \"_measurement\"])\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: sum)\r\n  |> set(key: \"_field\", value: \"volume\")\r\n\r\nunion(tables: [data_open, data_close, data_high, data_low, data_vol])\r\n"
    }
   ]
  }
 ]
}