{
 "title": "Demo - InfluxDB2 - Markets",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TSE Index",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"market_tick\")\r\n  |> filter(fn: (r) => r.code == \"001\")\r\n  |> filter(fn: (r) => r._field == \"Close\")\r\n  |> drop(columns: [\"code\", \"_measurement\"])\r\n"
    },
    {
     "query": "from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"market_tick\")\r\n  |> filter(fn: (r) => r.code == \"001\")\r\n  |> filter(fn: (r) => r._field == \"Amount\")\r\n  |> drop(columns: [\"code\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "FS Spread (%)",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "t_index = from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"market_tick\")\r\n  |> filter(fn: (r) => r.code == \"001\")\r\n  |> filter(fn: (r) => r._field == \"Close\")\r\n  |> last()\r\n\r\nt_fut = from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"tick\")\r\n  |> filter(fn: (r) => r.code == \"TXFD2\" or r.code == \"TXFE2\" or r.code == \"TXFF2\")\r\n  |> filter(fn: (r) => r._field == \"close\")\r\n  |> last()\r\n\r\njoin(\r\n  tables: {ind:t_index, fut:t_fut},\r\n  on: [\"_stop\"]\r\n)\r\n  |> map(fn: (r) => ({code: r.code_fut, \"%\": (float(v: r._value_fut) / float(v: r._value_ind) -1.0)*100.0 }))"
    }
   ]
  },
  {
   "title": "Bid Over Ask Volume (Buy/Sell Power)",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "import \"math\"\r\nfrom(bucket:\"sino_quotes\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"orderbook\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\", \"code\"],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n  //|> drop(columns: [\"_stop\", \"_start\", \"_measurement\", \"_time\"])\r\n  |> map(\r\n    fn: (r) => ({ r with \r\n        bid_over_ask: if (r.ask1_vol + r.ask2_vol + r.ask3_vol + r.ask4_vol + r.ask5_vol) > 0 then\r\n            100.0 * (float(v: r.bid1_vol + r.bid2_vol + r.bid3_vol + r.bid4_vol + r.bid5_vol) / float(v: r.ask1_vol + r.ask2_vol + r.ask3_vol + r.ask4_vol + r.ask5_vol) - 1.0)\r\n        else\r\n            0.0,\r\n    }),\r\n  )\r\n  |> keep(columns: [\"code\", \"bid_over_ask\"])\r\n  |> group()\r\n  |> sort(columns: [\"bid_over_ask\"], desc: true)"
    }
   ]
  },
  {
   "title": "Quote",
   "type": "table",
   "gridPos": { "h": 17, "w": 18, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"tick\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\", \"code\"],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n  |> drop(columns: [\"_stop\", \"_start\", \"_measurement\", \"_time\"])\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Stream",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "buffer": 300000,
     "channel": "stream/gf_pusher/sino/orderbook/2330",
     "filter": {
      "fields": []
     }
    }
   ]
  }
 ]
}