{
 "title": "Demo Influxdb",
 "time": { "from": "2022-03-25T03:36:51.150Z", "to": "2022-03-25T06:06:09.174Z" },
 "templating": {
  "list": [
   {
    "name": "Code",
    "label": "Code",
    "query": "from(bucket:\"sino_quotes\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"tick\")\r\n  |> last()\r\n  |> keep(columns: [\"code\"])\r\n  |> group()\r\n  |> distinct(column: \"code\")\r\n  "
   },
   { "name": "Kbar_Freq", "query": "1s, 1m, 5m, 15m, 1h, 1d" }
  ]
 },
 "panels": [
  {
   "title": "Tick",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"tick\")\r\n  |> filter(fn: (r) => r.code == ${Code:doublequote})\r\n  |> filter(fn: (r) => r._field == \"close\")\r\n  |> drop(columns: [\"code\", \"_measurement\"])\r\n"
    },
    {
     "query": "from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"tick\")\r\n  |> filter(fn: (r) => r.code == ${Code:doublequote})\r\n  |> filter(fn: (r) => r._field == \"volume\")\r\n  |> drop(columns: [\"code\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "OHLCV",
   "type": "candlestick",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "data = from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"tick\")\r\n  |> filter(fn: (r) => r.code == ${Code:doublequote})\r\n  |> filter(fn: (r) => r._field == \"close\")\r\n  |> drop(columns: [\"code\", \"_measurement\"])\r\n\r\ndata_open = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: first)\r\n  |> set(key: \"_field\", value: \"open\")\r\n\r\ndata_close = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: last)\r\n  |> set(key: \"_field\", value: \"close\")\r\n\r\ndata_high = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: max)\r\n  |> set(key: \"_field\", value: \"high\")\r\n\r\ndata_low = data\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: min)\r\n  |> set(key: \"_field\", value: \"low\")\r\n\r\n\r\ndata_vol = from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"tick\")\r\n  |> filter(fn: (r) => r.code == ${Code:doublequote})\r\n  |> filter(fn: (r) => r._field == \"volume\")\r\n  |> drop(columns: [\"code\", \"_measurement\"])\r\n  |> aggregateWindow(every: ${Kbar_Freq}, fn: sum)\r\n  |> set(key: \"_field\", value: \"volume\")\r\n\r\nunion(tables: [data_open, data_close, data_high, data_low, data_vol])\r\n"
    }
   ]
  },
  {
   "title": "Quote",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket:\"sino_quotes\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"tick\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\", \"code\"],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n  |> drop(columns: [\"_stop\", \"_start\", \"_measurement\", \"_time\"])\r\n  |> group()\r\n  \r\n  |> map(\r\n    fn: (r) => ({ \r\n      r with mid_prc: 0.5*(r.ask + r.bid)\r\n    })\r\n  )"
    }
   ]
  },
  {
   "title": "Quote",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "query": "from(bucket:\"sino_quotes\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"h_tick\")\r\n  |> filter(fn: (r) => r._field == \"bid_vol\" or r._field == \"ask_vol\" or r._field == \"vol\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\", \"code\"],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n  |> drop(columns: [\"_stop\", \"_start\", \"_measurement\", \"_time\"])\r\n  |> group()\r\n  \r\n  |> map(\r\n    fn: (r) => ({ \r\n      r with vol_pct: float(v: r.vol) / (float(v: r.bid_vol) + float(v: r.ask_vol))*100.0\r\n    })\r\n  )\r\n  |> drop(columns: [\"vol\", \"ask_vol\", \"bid_vol\"])"
    }
   ]
  },
  {
   "title": "Stream",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "buffer": 300000,
     "channel": "stream/gf_pusher/sino/tick/MXFD2",
     "filter": {
      "fields": []
     }
    }
   ]
  }
 ]
}