{
 "title": "Demo - Markets",
 "time": { "from": "2022-03-25T01:00:00.000Z", "to": "2022-03-25T05:30:00.000Z" },
 "panels": [
  {
   "title": "001 & TXF Tick / Spread or Buy - Sell count",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"tick\")\r\n  |> filter(fn: (r) => r.code == ${Code:doublequote})\r\n  |> filter(fn: (r) => r._field == \"close\")\r\n  |> drop(columns: [\"code\", \"_measurement\"])\r\n"
    },
    {
     "query": "from(bucket:\"sino_quotes\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"h_tick\")\r\n  |> filter(fn: (r) => r.code == ${Code:doublequote})\r\n  |> filter(fn: (r) => r._field == \"vol\")\r\n  |> set(key: \"_field\", value: \"volume\")\r\n  |> drop(columns: [\"code\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "Buy/Sell Power",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"sino_quotes\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"h_tick\")\r\n  |> filter(fn: (r) => r._field == \"bid_vol\" or r._field == \"ask_vol\" or r._field == \"vol\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\", \"code\"],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n  |> drop(columns: [\"_stop\", \"_start\", \"_measurement\", \"_time\"])\r\n  |> group()\r\n  \r\n  |> map(\r\n    fn: (r) => ({ \r\n      r with vol_pct: float(v: r.vol) / (float(v: r.bid_vol) + float(v: r.ask_vol))*100.0\r\n    })\r\n  )\r\n  |> drop(columns: [\"vol\", \"ask_vol\", \"bid_vol\"])\r\n  |> sort(columns: [\"vol_pct\"], desc: true)"
    }
   ]
  },
  {
   "title": "Quote",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket:\"sino_quotes\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r._measurement == \"h_tick\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\", \"code\"],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n  |> drop(columns: [\"_stop\", \"_start\", \"_measurement\", \"_time\"])\r\n  |> group()\r\n  \r\n  |> map(\r\n    fn: (r) => ({ \r\n      r with mid_prc: 0.5*(r.ask + r.bid)\r\n    })\r\n  )"
    }
   ]
  },
  {
   "title": "Stream",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "buffer": 300000,
     "channel": "stream/gf_pusher/sino/tick/MXFD2",
     "filter": {
      "fields": []
     }
    }
   ]
  }
 ]
}