{
 "title": "Strategy - T5FNYF",
 "tags": [ "strategy" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "System Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select dt, strategy, quote_exchange_type, broker_exchange_type from shr_system_status where strategy=\"T5FNYF\""
    }
   ]
  },
  {
   "title": "status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select quote_alive, broker_alive, sandbox_mode from shr_system_status where strategy=\"T5FNYF\""
    }
   ]
  },
  { "title": "Quote", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Quote",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "select time(dt) as dt, symbol, bid1_vol, bid1, ask1 ,ask1_vol from snapshot_twse_orderbook_fop"
    }
   ]
  },
  {
   "title": "Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 6 },
   "targets": [
    {
     "rawSql": "login(\"admin\", \"123456\"); \nselect convertTZ(timestamp(dt), \"Asia/Taipei\", \"Etc/GMT\"), 0.5*(ask1+bid1) as NYF from loadTable(\"dfs://twse/orderbook_fop\", \"orderbook_fop\") where symbol=\"NYFC2\",ask1>0, bid1>0, timestamp(dt) between $__timeFilter"
    },
    {
     "rawSql": "login(\"admin\", \"123456\"); \nselect convertTZ(timestamp(dt), \"Asia/Taipei\", \"Etc/GMT\"), 0.5*(ask1+bid1) as T5F from loadTable(\"dfs://twse/orderbook_fop\", \"orderbook_fop\") where symbol=\"T5FC2\",ask1>0, bid1>0, timestamp(dt) between $__timeFilter"
    }
   ]
  },
  {
   "title": "Signal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 14 },
   "targets": [
    {
     "rawSql": "select convertTZ(timestamp(dt), \"Asia/Taipei\", \"Etc/GMT\"), bench_bid from signal_sprd_t5fnyf where timestamp(dt) between $__timeFilter, replay=0"
    },
    {
     "rawSql": "select convertTZ(timestamp(dt), \"Asia/Taipei\", \"Etc/GMT\"), bench_ask from signal_sprd_t5fnyf where timestamp(dt) between $__timeFilter, replay=0"
    },
    {
     "rawSql": "select convertTZ(timestamp(dt), \"Asia/Taipei\", \"Etc/GMT\"), diff_bid from signal_sprd_t5fnyf where timestamp(dt) between $__timeFilter, replay=0"
    },
    {
     "rawSql": "select convertTZ(timestamp(dt), \"Asia/Taipei\", \"Etc/GMT\"), diff_ask from signal_sprd_t5fnyf where timestamp(dt) between $__timeFilter, replay=0"
    }
   ]
  },
  {
   "title": "Open PnL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 22 },
   "targets": [
    {
     "rawSql": "select convertTZ(timestamp(dt), \"Asia/Taipei\", \"Etc/GMT\"), open_pnl from signal_sprd_t5fnyf where timestamp(dt) between $__timeFilter, replay=0"
    },
    {
     "rawSql": "select convertTZ(timestamp(dt), \"Asia/Taipei\", \"Etc/GMT\"), position from signal_sprd_t5fnyf where timestamp(dt) between $__timeFilter, replay=0"
    }
   ]
  },
  { "title": "Account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Account Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "select * from sino_account_info where left(account_id, 4)=\"sino\""
    }
   ]
  },
  {
   "title": "Position",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "select dt, account_id, strategy, symbol, side, volume, prc_break_even from shr_position where strategy=\"T5FNYF\""
    }
   ]
  },
  {
   "title": "Open PnL",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "login(`admin, `123456); select * from get_open_pnl(\"sino\")"
    }
   ]
  },
  {
   "title": "Closed PnL (from contract start)",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "rawSql": "login(\"admin\", \"123456\"); get_all_closed_pnl_contract(\"sino\")"
    }
   ]
  },
  { "title": "Order & Trade", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Order",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "select dt, strategy, symbol, side, price, volume, status from shr_order where strategy=\"T5FNYF\", dt between $__timeFilter"
    }
   ]
  },
  {
   "title": "Trade",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "rawSql": "login('admin', '123456');\nselect dt, strategy, symbol, side, price, volume from loadTable(\"dfs://accounts/trade\", \"trade\") where strategy=\"T5FNYF\", dt between $__timeFilter"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "log - trade system",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "container_name: \"/strategy_TS\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}