apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    editable: true


  - name: influxdb
    type: influxdb
    access: proxy
    isDefault: true
    url: http://influxdb:8086
    secureJsonData:
      token: btoMns5-o__S3C0xlB6RIMTpsjxpAefNMaWftWJrMh243m0PtnHIh1DLyGh_io82c2TcRGEjbYFAJs0qlyzHZw==
    jsonData:
      version: Flux
      organization: trade_view
      tlsSkipVerify: false
      withCredentials: false
    editable: true

  - name: PostgreSQL
    type: postgres
    url: http://postgres:5432
    user: postgres
    secureJsonData:
      password: password
    jsonData:
      sslmode: "verify-full"
      timescaledb: true
      postgresVersion: "12+"
    editable: true